### ISSUE TITLE
Queries are pulling down too many fields

### ISSUE THREAD

**Issue by Arithmomaniac** [tsdservices/Gravity#56]
https://github.com/tsdservices/Gravity/blob/075de8e177e33c903227f00bf58863484e59649e/Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs#L36

@jhightower pointed out to me that this line is wrong. When doing RSAPI reads/queries, we only want to return the fields on the relevant `BaseDto` type.

**Comment by hhristov-tsd** [comment]
I was thinking that we could add:

`public static List<FieldValue> GetPropertiesAsFieldValues<T>() where T : BaseDto
        {
            List<FieldValue> baseDtoFieldValues = new List<FieldValue>();

            foreach (PropertyInfo property in typeof(T).GetPublicProperties())
            {
                baseDtoFieldValues.Add(new FieldValue(property.GetFieldGuidValueFromAttribute()));
            }

            return baseDtoFieldValues;
        }`

As static in the BaseDto and pass `BaseDto.GetPropertiesAsFieldValues<T>()` to the Query, instead of `Fields = FieldValue.AllFields`. 

There possibly is a better way of naming it though. As we are not actually getting a full FieldValue List in this case, but rather a 'Blank' one which could be used for GET.

Do you guys think this is appropriate?

**Comment by hhristov-tsd** [comment]
Looks better, yup. Forgot about the "GetFieldGuids" option.

**Comment by mrobustelli** [comment]
Need tests around this as part of "Done" to verify correct stuff being returned.
